version: "3"
 
volumes: # 自定义数据卷，位于宿主机/var/lib/docker/volumes内
  myproject_db_vol: # 定义数据卷同步容器内mysql数据
  myproject_redis_vol: # 定义数据卷同步redis容器内数据
  myproject_media_vol: # 定义数据卷同步media文件夹数据
services:

  db:
    image: mysql:5.7
    environment:
       - MYSQL_ROOT_PASSWORD=root # 数据库密码
       - MYSQL_DATABASE=mysite6 # 数据库名称

    volumes:
       - myproject_db_vol:/var/lib/mysql:rw # 挂载数据库数据, 可读可写
       - ./compose/mysql/conf/my.cnf:/etc/mysql/my.cnf # 挂载配置文件
       - ./compose/mysql/init:/docker-entrypoint-initdb.d/ # 挂载数据初始化sql脚本
    ports:
       - "3306:3306"
    restart: always
    
  web:
    build: ./mysite6
    expose:
       - "8000"
    volumes:
       - ./mysite6:/var/www/html/mysite6 # 挂载项目代码
       - ./compose/uwsgi:/tmp # 挂载uwsgi日志
    links:
       - db
    depends_on: # 依赖关系
       - db
    environment:
       - DEBUG=False
    restart: always
    tty: true
    stdin_open: true
 
  nginx:
    build: ./compose/nginx
    ports:
       - "80:80"
       - "443:443"
    expose:
       - "80"
    volumes:
       - ./compose/nginx/ssl:/usr/share/nginx/ssl # 挂载ssl证书目录
       - ./compose/nginx/log:/var/log/nginx # 挂载日志
    links:
       - web
    depends_on:
       - web
    restart: always